repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.11.11'
    hooks:
      - id: ruff
        name: ruff (lint)
        args: [--fix]
        files: ^backend/
      - id: ruff-format
        name: ruff (format)
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.27.0'
    hooks:
      - id: eslint
        name: eslint (frontend)
        files: ^frontend/.*\.(js|vue)$
        types: [file]
        args: [--fix, --config, frontend/eslint.config.js]
        additional_dependencies:
          - eslint@9.27.0
          - eslint-plugin-vue@10.1.0
          - eslint-config-prettier@10.1.5

  - repo: local
    hooks:
      - id: prettier-frontend
        name: prettier (frontend)
        entry: npx prettier --write
        language: node
        language_version: system
        files: ^frontend/.*\.(js|vue|css|scss|html|json)$
        types_or: [javascript, vue, css, scss, html, json]
