# Generated by Django 4.2.4 on 2023-08-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_image_is_liked_gallery_image_likes_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date']},
        ),
    ]
