# Generated by Django 4.2.4 on 2025-06-21 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_uservisit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uservisit",
            name="email",
        ),
        migrations.AddField(
            model_name="uservisit",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
