# Generated by Django 4.2.4 on 2023-08-29 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='liked_by_users',
            field=models.ManyToManyField(related_name='liked_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
