name: Daily APOD scrapper

on:
  schedule:
    - cron: "0 * * * *" # Run every day at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  update-apod:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Set environment variables
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

      - name: Run APOD scrapper script
        run: python backend/utils/scrape_apod.py

      - name: Commit and push if changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          DATE=$(date +'%d-%m-%Y')
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add entry $DATE to JSON"  && git push)
